---

- name: PDNS 4.7
  hosts: pdns
  vars_files:
    - ../resources/vars/pdns-common.yml
    - ../resources/vars/pdns-repo-47.yml
    - ../resources/vars/pdns-backends.yml
  roles:
    - { role: powerdns.pdns }
