---

- block:

  - name: Prefix the version with the correct separator on RedHat
    set_fact:
      pdns_package_version: "-{{ pdns_package_version }}"
    when: ansible_os_family == 'RedHat'

  - name: Prefix the version with the correct separator on Debian
    set_fact:
      pdns_package_version: "={{ pdns_package_version }}"
    when: ansible_os_family == 'Debian'

  when: pdns_package_version != ''
  tags:
    - install

- name: Install PowerDNS
  package:
    name: "{{ pdns_package_name }}{{ pdns_package_version }}"
    state: present
  tags:
    - install

- name: Install the PowerDNS backends
  package:
    name: "{{ pdns_backends_packages[item.key.split(':')[0]] }}{{ pdns_package_version }}"
    state: present
  when: pdns_backends_packages[item.key.split(':')[0]] is defined
  with_dict: "{{ pdns_backends }}"
  tags:
    - install
