---

- name: PDNS master
  hosts: pdns
  vars_files:
    - ../resources/vars/pdns-common.yml
    - ../resources/vars/pdns-repo-master.yml
    - ../resources/vars/pdns-backends.yml
  roles:
    - { role: powerdns.pdns }
