# Molecule managed

FROM {{ item.image }}

ENV container docker

RUN dnf makecache && \
    dnf install -y systemd python3 python3-pip sudo bash vim iproute procps-ng hostname && \
    rm -Rf /usr/share/doc && \
    rm -Rf /usr/share/man && \
    dnf clean all

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Create the `ansible` connection user with passwordless sudo. The sudoers drop-in
# replaces editing the distribution's default %wheel or %sudo line, which differs
# per family and is silently ineffective if that line ever changes.
ENV ANSIBLE_USER=ansible
RUN set -xe && \
    groupadd -r ${ANSIBLE_USER} && \
    useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
    printf '%s ALL=(ALL) NOPASSWD:ALL\n' "${ANSIBLE_USER}" > /etc/sudoers.d/${ANSIBLE_USER} && \
    chmod 0440 /etc/sudoers.d/${ANSIBLE_USER}

VOLUME [ "/sys/fs/cgroup", "/tmp", "/run" ]

CMD [ "/usr/sbin/init" ]
