# Molecule managed

FROM {{ item.image }}

ENV container docker

RUN dnf makecache && \
    dnf install -y systemd python3 python3-pip sudo bash vim iproute procps-ng hostname && \
    rm -Rf /usr/share/doc && \
    rm -Rf /usr/share/man && \
    dnf clean all

RUN cd /lib/systemd/system/sysinit.target.wants/; \
    for i in *; do [ $i = systemd-tmpfiles-setup.service ] || rm -f $i; done

RUN rm -f /lib/systemd/system/multi-user.target.wants/* \
    /etc/systemd/system/*.wants/* \
    /lib/systemd/system/local-fs.target.wants/* \
    /lib/systemd/system/sockets.target.wants/*udev* \
    /lib/systemd/system/sockets.target.wants/*initctl* \
    /lib/systemd/system/basic.target.wants/* \
    /lib/systemd/system/anaconda.target.wants/*

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Approve local accounts before the shadow based account check of sudo.
#
# Molecule connects as root and only calls sudo to drop to a service account,
# for instance `become_user: pdns`. On the CI hosts the account phase of
# pam_unix cannot retrieve the shadow data of the local accounts of these images
# and aborts sudo with "PAM account management error: Authentication service
# cannot retrieve authentication info". pam_localuser approves any account that
# exists in /etc/passwd, which covers every user sudo can set as PAM_USER here:
# the invoking user, root and the service account.
#
# Only the account phase of sudo is short-circuited. Authentication, password
# and session handling, the shared system-auth stack and the sudoers policy are
# untouched, and accounts that do not exist locally are still rejected.
RUN sed -i '0,/^account/s//account    sufficient   pam_localuser.so\naccount/' /etc/pam.d/sudo

# Create `ansible` user with sudo permissions
ENV ANSIBLE_USER=ansible SUDO_GROUP=wheel
RUN set -xe && \
    groupadd -r ${ANSIBLE_USER} && \
    useradd -m -g ${ANSIBLE_USER} ${ANSIBLE_USER} && \
    usermod -aG ${SUDO_GROUP} ${ANSIBLE_USER} && \
    sed -i "/^%${SUDO_GROUP}/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers

VOLUME [ "/sys/fs/cgroup", "/tmp", "/run" ]

CMD [ "/usr/sbin/init" ]
