---

- name: Prepare the Molecule Test Resources
  hosts: pdns
  tasks:
    # Make sure the default MySQL and SQLite
    # schemas are installed in /usr/share/doc/
    - name: Disable the YUM 'nodocs' option
      ansible.builtin.lineinfile:
        line: tsflags=nodocs
        dest: /etc/yum.conf
        state: absent
      when: ansible_pkg_mgr == 'yum'

    - name: Disable the APT 'nodoc' option
      ansible.builtin.lineinfile:
        line: path-exclude=/usr/share/doc/*
        dest: /etc/dpkg/dpkg.cfg.d/excludes
        state: absent

    # Install rsyslog to capture the PowerDNS Recursor log messages
    # when the service is not managed by systemd
    - name: Install rsyslog
      when: ansible_service_mgr != 'systemd'
      block:
        - name: Install rsyslog
          ansible.builtin.package:
            name: rsyslog
            state: present

        - name: Start rsyslog
          ansible.builtin.service:
            name: rsyslog
            state: started

    - name: Install dnspython and acl on Debian/Ubuntu
      ansible.builtin.apt:
        name:
          - python3-dnspython
          - acl
        state: present
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install dnspython on RHEL/Alma/Rocky/OL
      ansible.builtin.dnf:
        name: python3-dns
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Install dnspython on Archlinux
      ansible.builtin.package:
        name: python-dnspython
        state: present
      when: ansible_pkg_mgr == 'pacman'
