---

- name: Prepare the Molecule Test Resources
  hosts: pdns
  tasks:
    # This is required to be sure yum install the
    # default MySQL and SQLite schemas in /usr/share/doc/
    - name: Disable the YUM 'nodocs' option
      lineinfile:
        line: tsflags=nodocs
        path: /etc/yum.conf
        state: absent
      when: ansible_pkg_mgr == 'yum'
