---

scenario:
 name: systemd-no-overrides

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: debian-11
    groups: ["pdns"]
    image: debian:11
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    dockerfile_tpl: debian-systemd
    environment: { container: docker }

  - name: debian-12
    groups: ["pdns"]
    image: debian:12
    privileged: True
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /run/lock
      - /tmp
    dockerfile_tpl: debian-systemd
    environment: { container: docker }

  - name: ubuntu-2204
    groups: ["pdns"]
    image: ubuntu:22.04
    tmpfs:
      - /run
      - /tmp
    dockerfile_tpl: debian-systemd

  - name: ubuntu-2404
    groups: ["pdns"]
    image: ubuntu:24.04
    tmpfs:
      - /run
      - /tmp
    dockerfile_tpl: debian-systemd

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: .ansible_cache
      fact_caching_timeout: 7200
    ssh_connection:
      pipelining: true
  inventory:
    links:
      host_vars: ../resources/host_vars/
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint: ansible-lint -x ANSIBLE0006 ANSIBLE0016 306

lint: yamllint defaults tasks meta vars

verifier:
  name: testinfra
  options:
    hosts: "pdns"
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to 'directory'
    - ../systemd-no-override
