---

scenario:
  name: pdns-os-repos

driver:
  name: docker

dependency:
  name: galaxy

platforms:

  - name: archlinux
    groups: ["pdns"]
    image: archlinux:base
    dockerfile_tpl: archlinux-systemd

  # In order to run the tests we need
  # a MySQL container to be up & running
  - name: mysql
    image: mysql:8.4.8
    env:
      MYSQL_ROOT_PASSWORD: pdns
      MYSQL_ROOT_HOST: '%'
    # Declaring the container as service,
    # will link it to the others containers on creation
    is_service: true

  # Additional service for gmysql tests against MariaDB 10.6
  - name: mariadb
    image: mariadb:10.6
    env:
      MARIADB_ROOT_PASSWORD: pdns
      MARIADB_ROOT_HOST: '%'
    is_service: true

  # PostgreSQL service for gpgsql backend tests
  - name: postgresql
    image: postgres:16
    env:
      POSTGRES_PASSWORD: pdns
    is_service: true

provisioner:
  name: ansible
  options:
    diff: true
    v: true
  config_options:
    defaults:
      gathering: smart
      fact_caching: jsonfile
      fact_caching_connection: .ansible_cache
      fact_caching_timeout: 7200
    ssh_connection:
      pipelining: true
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint: ansible-lint

lint: yamllint defaults tasks meta vars

verifier:
  name: testinfra
  options:
    hosts: "pdns"
    vvv: true
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to 'directory'
    - ../backend-sqlite/
    - ../backend-lmdb/
    - ../backend-mysql/
    - ../backend-mariadb/
    - ../backend-postgresql/
    - ../backend-bind/
    - ../backend-pipe/
    - ../backend-geoip/
    - ../backend-zones/
    - ../service-mask/
    - ../systemd-override/
