---

##
# PowerDNS Configuration
##

pdns_config:

  # Turns on primary operations
  primary: true

  # Listen Address
  local-address: "127.0.0.1"
  local-port: "53"

  # API Configuration
  api: true
  api-key: "powerdns"

  # Embedded webserver
  webserver: true
  webserver-address: "0.0.0.0"
  webserver-port: "8001"

pdns_service_overrides: {}
