---

# Pipe backend profile
pdns_backends_pipe:
  pipe:
    command: "{{ pdns_config_dir }}/pipe-backend.py"
    abi-version: 5

pdns_instance:
  service_name: "pdns@pipe"
  service_enabled: "no"
  config_file: "pdns-pipe.conf"
  config_name: "pipe"
  config_overrides:
    local-port: "59"
    webserver-port: "8007"
    zone-cache-refresh-interval: "0"
  zone: "pipe.test"

pdns_config_files_pipe:
  - dest: pipe-backend.py
    mode: "0750"
    content: |
      #!/usr/bin/env python3
      import sys


      def emit(text):
          sys.stdout.write(text + "\n")
          sys.stdout.flush()


      while True:
          line = sys.stdin.readline()
          if not line:
              break

          parts = line.rstrip("\n").split("\t")
          if not parts:
              continue

          if parts[0] == "HELO":
              if len(parts) > 1 and parts[1] == "5":
                  emit("OK\tpdns-ansible pipe backend")
              else:
                  emit("FAIL")
              continue

          if parts[0] != "Q":
              # Keep the coprocess alive for unsupported command types.
              emit("END")
              continue

          if len(parts) < 5:
              emit("END")
              continue

          qname = parts[1].rstrip(".").lower()
          qtype = parts[3].upper()
          qid = parts[4]

          scopebits = "0"
          auth = "1"

          if qname == "pipe.test":
              if qtype in ("ANY", "SOA"):
                  emit(f"DATA\t{scopebits}\t{auth}\tpipe.test\tIN\tSOA\t60\t{qid}\tns1.pipe.test hostmaster.pipe.test 2026022101 3600 1800 1209600 60")
              if qtype in ("ANY", "NS"):
                  emit(f"DATA\t{scopebits}\t{auth}\tpipe.test\tIN\tNS\t60\t{qid}\tns1.pipe.test")
              if qtype in ("ANY", "A"):
                  emit(f"DATA\t{scopebits}\t{auth}\tpipe.test\tIN\tA\t60\t{qid}\t127.0.0.59")
          elif qname == "ns1.pipe.test" and qtype in ("ANY", "A"):
              emit(f"DATA\t{scopebits}\t{auth}\tns1.pipe.test\tIN\tA\t60\t{qid}\t127.0.0.1")

          emit("END")

pdns_config_overrides_pipe: {}

pdns_backends: "{{ pdns_backends_pipe }}"
pdns_config_files: "{{ pdns_config_files_pipe }}"
