---

scenario:
  name: pdns-41

driver:
  name: docker

dependency:
  name: galaxy

platforms:
  - name: centos-6
    image: centos:6
    groups:
      - pdns

  - name: centos-7
    image: centos:7
    dockerfile_tpl: centos-systemd
    groups:
      - pdns

  - name: ubuntu-1604
    image: ubuntu:16.04
    dockerfile_tpl: debian-systemd
    groups:
      - pdns

  - name: ubuntu-1804
    image: ubuntu:18.04
    dockerfile_tpl: debian-systemd
    groups:
      - pdns

  - name: debian-8
    image: debian:8
    groups:
      - pdns

  - name: debian-9
    image: debian:9
    dockerfile_tpl: debian-systemd
    groups:
      - pdns

  # In order to run the tests we need
  # a MySQL container to be up & running
  - name: mysql
    image: mysql:5.7
    env:
      MYSQL_ROOT_PASSWORD: pdns
    # Declaring the container as service,
    # will link it to the others Platforms containers
    # on creation.
    is_service: yes

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: ../resources/create.yml
    destroy: ../resources/destroy.yml
    prepare: ../resources/prepare.yml
  lint:
    name: ansible-lint
    options:
      # excludes "systemctl used in place of systemd module"
      x: ["ANSIBLE0006"]

lint:
  name: yamllint

verifier:
  name: testinfra
  options:
    hosts: "pdns"
    vvv: True
  directory: ../resources/tests/all
  additional_files_or_dirs:
    # path relative to 'directory'
    - ../repo-41/
    - ../backend-sqlite/
    - ../backend-mysql/
  lint:
    name: flake8
