---

- name: Install PowerDNS
  hosts: pdns
  # Scenario specific viriables
  vars:
    pdns_install_repo: "{{ pdns_auth_powerdns_repo_41 }}"
  # Include the common variables
  vars_files:
    - ../common/playbook_vars.yml
  roles:
    - { role: pdns-ansible }
